In [1]:
import numpy as np
from scipy import linalg

In [2]:
def main():
    # ==============================================
    # 1. Matrix Operations with NumPy and SciPy
    # ==============================================
    print("\n" + "="*50)
    print("1. MATRIX OPERATIONS")
    print("="*50)

    # Define matrices
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

    print("\nMatrix A:\n", A)
    print("\nMatrix B:\n", B)

    # Addition
    add = A + B
    print("\nAddition (A + B):\n", add)

    # Subtraction
    sub = A - B
    print("\nSubtraction (A - B):\n", sub)

    # Multiplication (matrix product)
    mul = A @ B  # or np.dot(A, B)
    print("\nMatrix Multiplication (A @ B):\n", mul)

    # Element-wise multiplication
    elem_mul = A * B
    print("\nElement-wise Multiplication (A * B):\n", elem_mul)

    # Determinant
    det = np.linalg.det(A)
    print("\nDeterminant of A:", det)

    # Inverse
    inv = np.linalg.inv(A)
    print("\nInverse of A:\n", inv)

    # ==============================================
    # 2. Eigenvalues, Eigenvectors, and Orthogonality
    # ==============================================
    print("\n" + "="*50)
    print("2. EIGENVALUES AND EIGENVECTORS")
    print("="*50)

    # Define a symmetric matrix (for orthogonal eigenvectors)
    C = np.array([[2, -1], [-1, 2]])
    print("\nMatrix C:\n", C)

    # Calculate eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(C)

    print("\nEigenvalues:", eigenvalues)
    print("\nEigenvectors:\n", eigenvectors)

    # Check orthogonality of eigenvectors
    dot_product = np.dot(eigenvectors[:, 0], eigenvectors[:, 1])
    print("\nDot product of eigenvectors:", dot_product)

    # For symmetric matrices, eigenvectors should be orthogonal
    if abs(dot_product) < 1e-10:
        print("Eigenvectors are orthogonal (perpendicular)")
    else:
        print("Eigenvectors are not orthogonal")

    # ==============================================
    # 3. Span and Basis of a Vector Space
    # ==============================================
    print("\n" + "="*50)
    print("3. SPAN AND BASIS CALCULATION")
    print("="*50)

    # Define vectors
    v1 = np.array([1, 0, 0])
    v2 = np.array([0, 1, 0])
    v3 = np.array([1, 1, 0])
    v4 = np.array([0, 0, 1])  # Adding another vector for demonstration

    vectors = [v1, v2, v3, v4]
    print("\nOriginal vectors:")
    for i, v in enumerate(vectors, 1):
        print(f"v{i}:", v)

    # Create matrix with vectors as columns
    matrix = np.column_stack((v1, v2, v3, v4))

    # Calculate rank (dimension of the space spanned)
    rank = np.linalg.matrix_rank(matrix)
    print("\nRank of the matrix (dimension of span):", rank)

    # Find basis using QR decomposition
    Q, R, pivots = linalg.qr(matrix, pivoting=True)
    basis_indices = pivots[:rank]
    basis = matrix[:, basis_indices]

    print("\nBasis vectors (column indices):", basis_indices + 1)  # +1 for 1-based indexing
    print("\nBasis vectors:\n", basis)

    # Verify linear independence
    print("\nVerification - Rank of basis matrix:", np.linalg.matrix_rank(basis))


In [3]:
if __name__ == "__main__":
    main()


1. MATRIX OPERATIONS

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Addition (A + B):
 [[ 6  8]
 [10 12]]

Subtraction (A - B):
 [[-4 -4]
 [-4 -4]]

Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]

Element-wise Multiplication (A * B):
 [[ 5 12]
 [21 32]]

Determinant of A: -2.0000000000000004

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

2. EIGENVALUES AND EIGENVECTORS

Matrix C:
 [[ 2 -1]
 [-1  2]]

Eigenvalues: [3. 1.]

Eigenvectors:
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

Dot product of eigenvectors: -2.2371143170757382e-17
Eigenvectors are orthogonal (perpendicular)

3. SPAN AND BASIS CALCULATION

Original vectors:
v1: [1 0 0]
v2: [0 1 0]
v3: [1 1 0]
v4: [0 0 1]

Rank of the matrix (dimension of span): 3

Basis vectors (column indices): [3 4 1]

Basis vectors:
 [[1 0 1]
 [1 0 0]
 [0 1 0]]

Verification - Rank of basis matrix: 3
